language: go

go:
  - 1.3
  - release
  - tip

script:
  - go test -v ./...
  - cd cmd/ipfs && go install # test it can be compiled
  - cd ../../test/
  - make                      # sharness tests
  - cd ..

env: TEST_NO_FUSE=1
