sudo: required

dist: trusty

os:
  - linux
  - osx

go_import_path: github.com/ipfs/go-ipfs

language: go

go:
    - 1.5.2

before_install:
  - "if [ ${TRAVIS_OS_NAME:-'linux'} = 'linux' ]; then . ./.travis/before_install-linux.sh; fi"
  - "if [ ${TRAVIS_OS_NAME:-'linux'} = 'osx' ]; then . ./.travis/before_install-osx.sh; fi"

env:
  - TEST_VERBOSE=1 TEST_NO_IPV6=1 TEST_SUITE=test_go_expensive
  - TEST_VERBOSE=1 TEST_NO_IPV6=1 TEST_SUITE=test_sharness_expensive

install:
  - make toolkit_upgrade
  - make install

script:
  - make $TEST_SUITE

# For docker containers

services:
  - docker
