# dist: trusty # KVM Setup

notifications:
  email: false

os:
  - linux
  - osx

language: go

go:
    - 1.7

env:
  - TEST_NO_FUSE=1 TEST_VERBOSE=1 TEST_SUITE=test_go_expensive
  - TEST_NO_FUSE=1 TEST_VERBOSE=1 TEST_SUITE=test_sharness_expensive
  - BUILD=1

install:
  - make install

script:
  # Run the tests.
  - if [ -z "$BUILD" ]; then make $TEST_SUITE; fi
  # Build the snap.
  - if [ ! -z "$BUILD" ]; then docker run -v $(pwd):/cwd snapcore/snapcraft sh -c 'cd /cwd; snapcraft'; fi

# For docker containers.

sudo: required

services:
  - docker
