version: "{build}"

os: Windows Server 2012 R2

clone_folder: c:\gopath\src\github.com\ipfs\go-ipfs

environment:
  GOPATH: c:\gopath
  TEST_VERBOSE: 1
  global:
    BASH: C:\cygwin\bin\bash

install:
  - rmdir c:\go /s /q
  - appveyor DownloadFile https://storage.googleapis.com/golang/go1.5.2.windows-amd64.zip
  - 7z x go1.5.2.windows-amd64.zip -y -oC:\ > NUL
  - go env
  - go version

# Cygwin build script
#
# NOTES:
#
# The stdin/stdout file descriptor appears not to be valid for the Appveyor
# build which causes failures as certain functions attempt to redirect 
# default file handles. Ensure a dummy file descriptor is opened with 'exec'.
#  
build_script:
  - true

test_script:
  - '%BASH% -lc "cd $APPVEYOR_BUILD_FOLDER; exec 0</dev/null; export PATH=$GOPATH/bin:$PATH; export GOFLAGS=''-tags nofuse''; export TEST_NO_FUSE=1; export TEST_VERBOSE=1; export TEST_SUITE=test_sharness_expensive; make $TEST_SUITE"'
